### ISSUE TITLE
Can this tool read/write KeyFile?

### ISSUE THREAD

**Issue by hwy1992129** [open-lasso-python/lasso-python#58]
I don't find anything related to KeyFile in the documents....
The previous project qd-cae-python has it.
Will this capability be added into lasso-python?

**Comment by codie3611** [comment]
No we don't have it and no contributor has so far intended to do so. If someone wants to do it, it would be great though.
Most people do input file manipulation only based on a few string operations and don't need a fully capable key file composer so it is very niche. Another hurdle is, that parsing the key files is difficult as the format is very arbitrary such as varying field lengths or additional fields are all of a sudden present, so one has to go through the entire manual and program every edge case. And even then with every new version things might break due to alterations when new fields are added (seomtimes also undocumented). But hey we did the same pain with d3plot.
